name: postgres_driver
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: kernel <email@example.com>

environment:
  sdk: '>=2.10.4 <3.0.0'

dependencies:
  ffi: 1.0.0
  logging: 0.11.3+2
  resource_pool:
    git: https://github.com/radzish/resource_pool.git
  db_context_lib:
    git:
      url: https://github.com/radzish/db_context.git
      path: db_context_lib

dev_dependencies:
  pedantic: ^1.8.0+1
  test: ^1.9.4
  process_run: 0.10.6+1
  db_context_gen:
    git:
      url: https://github.com/radzish/db_context.git
      path: db_context_gen

dependency_overrides:
  db_context_lib:
    path: ../../db_context/db_context_lib
  db_context_gen:
    path: ../../db_context/db_context_gen
