name: postgres_driver
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.1.2
  logging: ^1.0.2
  db_context_lib:
    git:
      url: https://github.com/radzish/db_context.git
      path: db_context_lib

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.18.2
  process_run: ^0.12.2+1
  db_context_gen:
    git:
      url: https://github.com/radzish/db_context.git
      path: db_context_gen
