targets:
  $default:
    builders:
      postgres_driver_gen|transactional_generator:
        enabled: true

builders:
  transactional_generator:
    import: 'package:postgres_driver_gen/builder.dart'
    builder_factories: ['transactionalGenerator']
    build_extensions: { '.dart': ['.transactional.g.part'] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ['source_gen|combining_builder']
