name: postgres_driver_gen
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: kernel <email@example.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  build: ^1.2.2
  analyzer: '>=0.34.0 <0.39.0'
  postgres_driver:
    git:
      url: https://github.com/radzish/postgres_driver.git
      path: driver
  source_gen: ^0.9.4+6

dev_dependencies:
  pedantic: ^1.9.0
  build_runner: ^1.7.2
  build_test: ^0.10.10
  test: ^1.9.4
